### ISSUE TITLE
占位文字和图片的动画问题

### ISSUE THREAD

**Issue by Easyzhan** [ws00801526/XMNViews#2]
点击某处进入有textfiled的界面的时候,placehoder占位的文字和图片直接是在框上的,要交替点击输入框才能出现动画

**Comment by ws00801526** [comment]
不好意思,能提供下图片么

**Comment by Easyzhan** [comment]
![bug](https://cloud.githubusercontent.com/assets/8928783/17797845/d0e8d8f8-65fe-11e6-97ef-aa738ea3fa2d.png)
并未进行任何输入的时候

**Comment by Easyzhan** [comment]
图标和文字应该是在框里的吧,用户点击输入的时候再上去~😃

**Comment by ws00801526** [comment]
你这边是不是设置了state字段了

**Comment by Easyzhan** [comment]
貌似没有,我在进入控制器的时候会去设置找nsdefault里的值设置了空值

**Comment by ws00801526** [comment]
那就是因为你这边设置了空值的问题, 你设置的空值 其实是  @""空字符串   你需要设置nil

**Comment by Easyzhan** [comment]
恩,果然是这个原因,判断一下如果为空就不设置值就正常了😜多谢~

**Comment by ws00801526** [comment]
不客气
